// AWS Amplify Configuration
// This file will be auto-generated by Amplify CLI
// For deployment, run: amplify init && amplify push

export const awsconfig = {
  Auth: {
    Cognito: {
      userPoolId: process.env.VITE_COGNITO_USER_POOL_ID || '',
      userPoolClientId: process.env.VITE_COGNITO_USER_POOL_CLIENT_ID || '',
      region: process.env.VITE_AWS_REGION || 'ap-south-1',
      identityPoolId: process.env.VITE_COGNITO_IDENTITY_POOL_ID || ''
    }
  },
  API: {
    endpoints: [
      {
        name: 'YojanaMitraAPI',
        endpoint: process.env.VITE_API_ENDPOINT || 'https://api.yojanamitra.com',
        region: process.env.VITE_AWS_REGION || 'ap-south-1'
      }
    ]
  },
  Storage: {
    S3: {
      bucket: process.env.VITE_S3_BUCKET || '',
      region: process.env.VITE_AWS_REGION || 'ap-south-1'
    }
  }
};

// Bedrock Configuration
export const bedrockConfig = {
  region: process.env.VITE_AWS_REGION || 'ap-south-1',
  models: {
    primary: 'anthropic.claude-3-5-sonnet-20241022-v2:0',
    fallback: 'meta.llama3-1-8b-instruct-v1:0'
  },
  maxTokens: 1024
};

// Feature Flags
export const featureFlags = {
  useBedrockAsPrimary: true,
  useGeminiAsFallback: true,
  enableVoiceInput: true,
  enableDocumentUpload: true
};
